### ISSUE TITLE
Not working with ghc 7.8.4

### ISSUE THREAD

**Issue by Javran** [danr/contracts#3]
Cannot compile the current verion of hcc with ghc 7.8.4.
The following error raised during compilation:

```
[ 9 of 45] Compiling Halo.Shared      ( halo/src/Halo/Shared.hs, dist/build/hcc/hcc-tmp/Halo/Shared.o )

halo/src/Halo/Shared.hs:44:29: Not in scope: ‘tracingDynFlags’
```

After changing the missing definition to `undefined`, I got another error:

```
[27 of 45] Compiling Halo.PrimCon     ( halo/src/Halo/PrimCon.hs, dist/build/hcc/hcc-tmp/Halo/PrimCon.o )

halo/src/Halo/PrimCon.hs:40:6:
    Not in scope: data constructor ‘ADataCon’

halo/src/Halo/PrimCon.hs:73:10:
    Not in scope: ‘mkDataConIds’
        Perhaps you meant one of these:
          ‘mkDataCon’ (imported from DataCon),
          ‘mkDataConRep’ (imported from MkId),
          ‘eqDataConId’ (imported from TysWiredIn)
```

**Comment by danr** [comment]
Thanks. This repository is not really mainained anymore.
The corresponding fixes to the `tracingDynFlags` and `ADataCon` errors are in danr/hipspec@215daaaa6585af5c683d6ef0e181bb58c3bf2500
I'm not familiar with the `mkDataConIds` problem, though.
